name: Update server

on:
  pull_request:
    branches:
      - main
    paths:
      - 'language-server/package.json'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  download-server:
    name: Download and update server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep

      - name: Run download-server.sh script
        run: |
          ./download-server.sh

      - name: Check for modified files
        id: git-check
        run: echo "GIT_MODIFIED=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - name: Update changes in the PR
        if: steps.git-check.outputs.GIT_MODIFIED == 'true'
        run:  |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m '[automated commit] update schema'
          git push
